### ISSUE TITLE
GPU cache example crashes on X11

### ISSUE THREAD

**Issue by lux01** [dylanede/rusttype#10]
The GPU example fails to run on (probably) all X11 systems due to a [known bug][bug] in glutin. In short, GLX implementations seem to always report that sRGB is unsupported even when the format supports it.

The workaround until the bug is solved in glutin is to remove [this line][line].

[bug]: https://github.com/tomaka/glutin/issues/581
[line]: https://github.com/dylanede/rusttype/blob/205def21e370e35e2b860eb6f086fda749e57df8/examples/gpu_cache.rs#L68

Build output (with rustc 1.7.0 stable) on Xubutnu 15.10:
```
$ cargo run --example gpu_cache
     Running `target/debug/examples/gpu_cache`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: BackendCreationError(NoAvailablePixelFormat)', ../src/libcore/result.rs:688
Process didn't exit successfully: `target/debug/examples/gpu_cache` (exit code: 101)
```

**Comment by dylanede** [comment]
Hmm. The behaviour is also a bit suspect on OS X, in that it seems to be enabled regardless. I'll update the example.
