### ISSUE TITLE
Upgrade from ndarray 0.3

### ISSUE THREAD

**Issue by bluss** [dylanede/rusttype#13]
This is just a notice since ndarray's 0.3 versions now have a future incompatibility warning like this:

```rust
src/lib.rs:366:5: 366:86 warning: the trait bound `Self: std::marker::Sized` is not satisfied, #[warn(unsized_in_tuple)] on by default
src/lib.rs:366     unsafe fn clone_with_ptr(&self, ptr: *mut Self::Elem) -> (Self, *mut Self::Elem);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:366:5: 366:86 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
src/lib.rs:366:5: 366:86 note: for more information, see issue #33242 <https://github.com/rust-lang/rust/issues/33242>
```

which means that they will stop compiling at some point. (It was fixed in ndarray 0.5.1).

I was going to ask anyway, maybe ndarray should learn a default crate feature for numerics so that it is possible to depend on it without the numerics and maths related functionality?

**Comment by l1048576** [comment]
I sent PR #15 to remove dependency to ndarray.
At present, only `gpu_cache` module is using ndarray to hold 2D array of `u8`.
I thought ndarray is too powerful and it can be manually written.

I think ndarray is not necessary, but may it be used at other place or for other type than `OwnedArray<u8, (Ix, Ix)>`?)
