### ISSUE TITLE
Update crates.io version

### ISSUE THREAD

**Issue by ozkriff** [dylanede/rusttype#25]
ndarray 0.3 is not building on nightly rust: https://travis-ci.org/ozkriff/zoc/jobs/157466320 :(

**Comment by mitchmindtree** [comment]
@ozkriff it looks like rusttype hasn't been using ndarray since #15, however rusttype hasn't been published to crates.io in 6mths

@dylanede any chance you could publish a new version of rusttype to crates.io? This is causing travis to fail on the latest nightly at the conrod repo.

**Comment by dylanede** [comment]
Oh, yep, I'll do that shortly.

**Comment by dylanede** [comment]
Done.

**Comment by mitchmindtree** [comment]
Nice one, much appreciated!

**Comment by ozkriff** [comment]
@dylanede Thanks!
