### ISSUE TITLE
Space character (0x0020) has no extents

### ISSUE THREAD

**Issue by sharazam** [dylanede/rusttype#47]
When trying to get the extents of the space character of any font (Unicode 0x0020, a literal "space"), the glyphs `extents` are `None`, which is wrong (`freetype-rs` shows a height of 2000 units, FontForge confirms this). This makes it difficult to calculate the width of a space.

Seems to be a problem with `stb_truetype`. To reproduce:

```
let glyph = font.glyph(rusttype::CodepointOrGlyphId::Codepoint(rusttype::Codepoint(0x0020)));
let glyph_metrics = glyph.standalone().get_data().unwrap();
println!("{:?}", glyph_metrics.extents); // None - correct answer would be a Rect with a height of 2000
```

**Comment by sharazam** [comment]
It has something to do with `standalone` and the proxy system, not `stb_truetype`.

**Comment by sharazam** [comment]
Yes, this is an issue in stb_truetype, closing.

**Comment by khaledhosny** [comment]
A glyph with no contours has no extents by definition. I think you want the advance width which is independent from glyph extents and is encoded in the `hmtx` table.
