### ISSUE TITLE
Font::pair_kerning returns 0f32 for all glyph pairs

### ISSUE THREAD

**Issue by Lisoph** [dylanede/rusttype#54]
I found out through debugging that at [this line](https://github.com/dylanede/rusttype/blob/9f9dbcd82d49f6bfc2a6658179b2d693745f4a53/src/lib.rs#L410), both `id().0` expressions evaluate to `0` in my case, which is probably why the kerning computation fails.

Below is my layouting code which calls the pair_kerning function. It's very similar to the code used in the gpu_cache example. I also use the same font as in that example. What's important to note, is that my `g.id()` and `last_id` both are valid. 

```rust
/// Layout the glyphs like a paragraph with wrapping lines.
fn layout_paragraph<'a>(&'a self, font: &'a Font) -> Vec<PositionedGlyph<'a>> {
    let v_metrics = font.v_metrics(self.scale);
    let advance_y = v_metrics.ascent - v_metrics.descent + v_metrics.line_gap;

    let mut last_glyph: Option<GlyphId> = None;
    let mut caret = GlyphPoint { x: 0f32, y: 0f32 };
    let mut glyphs = Vec::new();

    for c in self.text.chars() {
        if c.is_control() {
            match c {
                '\n' => {
                    caret.x = 0f32;
                    caret.y += advance_y;
                }
                _ => {}
            }
        } else {
            if let Some(g) = font.glyph(c) {
                let g = g.scaled(self.scale);
                if let Some(last_id) = last_glyph {
                    caret.x += font.pair_kerning(self.scale, g.id(), last_id);
                }
                last_glyph = Some(g.id());

                let g = g.positioned(caret);
                glyphs.push(g);
            }
        }
    }

    glyphs
}
```

**Comment by alexheretic** [comment]
Perhaps kerning isn't doing what you expect, it is used to adjust the distance between two specific glyphs rather than provide the full distance. So it is valid that the value could be 0. You should get hold of a [`HMetrics`](https://dylanede.github.io/rusttype/rusttype/struct.HMetrics.html) struct which provides the `advance_width`. 

This is what's used to horizontally advance the caret in the examples, after adjusting for kerning.

```rust
// from examples/gpu_cache.rs:42
if let Some(id) = last_glyph_id.take() {
    caret.x += font.pair_kerning(scale, id, base_glyph.id());
}
last_glyph_id = Some(base_glyph.id());
let mut glyph = base_glyph.scaled(scale).positioned(caret);
// ...
caret.x += glyph.unpositioned().h_metrics().advance_width;
```

**Comment by Lisoph** [comment]
Hey @alexheretic, thanks for the quick reply. Indeed you are correct. I've adapted my code to the snipped you posted, and it's working now. I misunderstood the documentation to the pair_kerning function. `Returns additional kerning to apply as well as that given by HMetrics for a particular pair of glyphs.` I thought this meant that the h_metrics were also included in the result. Silly me.

Thanks a lot!
