### ISSUE TITLE
arithmetic operation overflow

### ISSUE THREAD

**Issue by Maxjen** [dylanede/rusttype#8]
I am getting an 'arithmetic operation overflowed' panic and the compiler is pointing me to [this line](https://github.com/dylanede/stb_truetype-rs/blob/master/src/lib.rs#L800). The example code I attached in issue #7 triggers it.(after cargo update)

It seems to be related to kerning, because the code works if I comment the following lines out:
```
for c in string.chars() {
    for c_other in string.chars() {
        let kerning = font.pair_kerning(scale, c, c_other);
        if kerning != 0.0 {
            println!("kerning {} {} {:.10} ", c, c_other, kerning);
        }
    }
}
```

**Comment by dylanede** [comment]
This works now. You now get a good list of kerning pairs for Deja Vu Sans.

**Comment by Maxjen** [comment]
Great! It looks much better now. Here is a [before and after](http://imgur.com/a/ysL7A). It's especially noticeable between the 'T' and the 'e'.

**Comment by dylanede** [comment]
Hey, that does look good! What is that project it's used in? Looks interesting. My main motivation for RustType is for a UI library project of mine.

**Comment by Maxjen** [comment]
It is also a UI that I am working on, which I intend to use for game editors. Here is the [link](https://github.com/Maxjen/inferno). But it is still at a very early stage. So far it only has the dock widget which is seen in the screenshot and even that isn't finished yet. But here is a [screenshot](http://imgur.com/a/ioLeF) of some more widgets that I want to have eventually. It's from an older [C++ project](https://github.com/Maxjen/Calamity) of mine.
